### ISSUE TITLE
Unclear usage

### ISSUE THREAD

**Issue by diamondman** [mekarpeles/pypc#16]
Following the usage in the github readme caused most files to be created in the parent directory of the project. 
I expected the command to create my project folder and populate it. Instead it expected me to be already in the project directory, like how git init works. 
Maybe a parameter should be added to allow creation of a new project as well as initializing an existing project.

**Comment by mekarpeles** [comment]
Clarified in readme -- https://github.com/mekarpeles/pypc/commit/8993051624493530483420cfe4a59ae59a55c5f2
